services:
  quotebank:
    build:
      context: .
    ports:
      - "8013:8000"
    volumes:
      - /DATA/AppData/quotebank/backend/uploads:/app/backend/uploads
      - /DATA/AppData/quotebank/quotebank.db:/app/quotebank.db
    env_file:
      - .env
    restart: unless-stopped
